# Components defined here are required to be kept in sync with hack/gen-versions/calico.go.tpl
title: master
components:
  libcalico-go:
    version: development
  typha:
    version: development
  calico/node:
    version: development
  calico/cni:
    version: development
  calico/kube-controllers:
    version: development
  flexvol:
    version: development
  calico/apiserver:
    version: development
  calico/windows-upgrade:
    version: development
