# Components defined here are required to be kept in sync with hack/gen-versions/calico.go.tpl
title: master
components:
  libcalico-go:
    version: base
  typha:
    version: base
  calico/node:
    version: base
  calico/cni:
    version: base
  calico/kube-controllers:
    version: base
  flexvol:
    version: base
  calico/apiserver:
    version: base
  calico/windows-upgrade:
    version: base
