# Components defined here are required to be kept in sync with hack/gen-versions/enterprise.go.tpl
title: master
components:
  libcalico-go:
    version: development
  cnx-manager:
    image: tigera/cnx-manager
    version: development
  voltron:
    image: tigera/voltron
    version: development
  cnx-apiserver:
    image: tigera/cnx-apiserver
    version: development
  cnx-queryserver:
    image: tigera/cnx-queryserver
    version: development
  cnx-kube-controllers:
    image: tigera/kube-controllers
    version: development
  typha:
    image: tigera/typha
    version: development
  cnx-node:
    image: tigera/cnx-node
    version: development
  fluentd:
    image: tigera/fluentd
    version: development
  fluentd-windows:
    image: tigera/fluentd-windows
    version: development
  es-proxy:
    image: tigera/es-proxy
    version: development
  es-gateway:
    image: tigera/es-gateway
    version: development
  dex:
    image: tigera/dex
    version: development
  eck-kibana:
    version: 7.16.2
  kibana:
    image: tigera/kibana
    version: development
  eck-elasticsearch:
    version: 7.16.2
  elasticsearch:
    image: tigera/elasticsearch
    version: development
  elastic-tsee-installer:
    image: tigera/intrusion-detection-job-installer
    version: development
  es-curator:
    image: tigera/es-curator
    version: development
  intrusion-detection-controller:
    image: tigera/intrusion-detection-controller
    version: development
  anomaly_detection_jobs:
    image: tigera/anomaly_detection_jobs
    version: development
  anomaly-detection-api:
    image: tigera/anomaly-detection-api
    version: development
  compliance-controller:
    image: tigera/compliance-controller
    version: development
  compliance-reporter:
    image: tigera/compliance-reporter
    version: development
  compliance-snapshotter:
    image: tigera/compliance-snapshotter
    version: development
  compliance-server:
    image: tigera/compliance-server
    version: development
  compliance-benchmarker:
    image: tigera/compliance-benchmarker
    version: development
  guardian:
    image: tigera/guardian
    version: development
  tigera-cni:
    image: tigera/cni
    version: development
  cloud-controllers:
    image: tigera/cloud-controllers
    version: development
  elasticsearch-metrics:
    image: tigera/elasticsearch-metrics
    version: development
  packetcapture:
    image: tigera/packetcapture
    version: development
  # coreos-prometheus holds the version of prometheus built for tigera/prometheus,
  # which prometheus operator uses to validate.
  coreos-prometheus:
    version: v2.32.0
  prometheus:
    image: tigera/prometheus
    version: development
  # coreos-prometheus holds the version of alertmanager built for tigera/alertmanager,
  # which prometheus operator uses to validate.
  coreos-alertmanager:
    version: v0.23.0
  alertmanager:
    image: tigera/alertmanager
    version: development
  tigera-prometheus-service:
    image: tigera/prometheus-service
    version: development
  deep-packet-inspection:
    image: tigera/deep-packet-inspection
    version: development
  windows:
    image: tigera/calico-windows-upgrade
    version: development
  # The components below are third-party images that have been retagged under
  # quay.io/tigera so all enterprise images come from the same repository and org.
  elasticsearch-operator:
    image: tigera/eck-operator
    version: development
  eck-elasticsearch-operator:
    version: 1.8.0
  l7-collector:
    image: tigera/l7-collector
    version: development
  envoy:
    image: tigera/envoy
    version: development
  dikastes:
    image: tigera/dikastes
    version: development
